apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.serviceName  }}
  labels:
    app: nginx-deployment-current
spec:
  ports:
    # - name: tcp
    - port: 443
  selector:
    app: nginx-deployment-current
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-current
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment-current
  template:
    metadata:
      labels:
        app: nginx-deployment-current
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: secret-volume
            - mountPath: /etc/nginx/conf.d
              name: configmap-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: nginx-certs-keys
        - name: configmap-volume
          configMap:
            name: nginxconfigmap