---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "a10-connector.fullname" . }}-secret
  annotations:
    {{- include "a10-connector.helm-annotations" . | nindent 2 }}
    {{- if .Values.metadata.podAnnotations }}
    {{ toYaml .Values.metadata.podAnnotations | trim | nindent 4 }}
    {{- end }}
  labels:
    {{- include "a10-connector.helm-labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secret.username | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}