
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "a10-connector.fullname" . }}-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "a10-connector.fullname" . }}-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "a10-connector.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ template "a10-connector.fullname" . }}-serviceaccount
    namespace: {{ template "a10-connector.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "a10-connector.fullname" . }}-clusterrole
rules:
  - apiGroups: ["*", "extensions","nodes","networking.k8s.io"]
    resources: ["secrets", "configmaps","endpoints","events","ingresses","ingresses/status","services","nodes"]
    verbs: ["get", "watch", "list","patch","create","update"]
  - apiGroups: ["slb.tkc.a10networks.com", "tkc.a10networks.com"]
    resources: ["natpools", "healthmonitors", "virtualservers", "servicegroups","serverssls", "virtualports","templateciphers","clientssls","serverssls/status","clientssls/status"]
    verbs: ["get", "watch", "list","patch","create","update"]